### ISSUE TITLE
Click on ooniprobe icon on drawer causes crash

### ISSUE THREAD

**Issue by Lymphatus** [TheTorProject/ooniprobe-android#57]
As for title, the app crashes if the icon is tapped. (Crash report below)

![screenshot_20170211-125731 copy](https://cloud.githubusercontent.com/assets/12133996/22853668/f266788a-f05c-11e6-96ce-403f6b395581.png)

It's un unhandled index in the code that sets the title, so I'm guessing it's supposed not to be clickable or just return nothing if tapped.
I think it should be another way to open the about window.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.openobservatory.ooniprobe, PID: 4318
                  java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
                      at org.openobservatory.ooniprobe.activity.MainActivity$override.selectItem(MainActivity.java:155)
                      at org.openobservatory.ooniprobe.activity.MainActivity$override.static$access$200(MainActivity.java:48)
                      at org.openobservatory.ooniprobe.activity.MainActivity$override.access$dispatch(MainActivity.java)
                      at org.openobservatory.ooniprobe.activity.MainActivity.access$200(MainActivity.java:0)
                      at org.openobservatory.ooniprobe.activity.MainActivity$DrawerItemClickListener.onItemClick(MainActivity.java:134)
                      at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                      at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
                      at android.widget.AbsListView$3.run(AbsListView.java:3879)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hellais** [comment]
Thanks for reporting this @Lymphatus!

I believe this should be fixed by https://github.com/TheTorProject/ooniprobe-android/commit/ffba289115bb2f9d5e72910f48a6ac2d419a46f3. It will be shipped as part of the new release.

I would suggest, though, we keep this issue open until the release is tagged and uploaded.

**Comment by Lymphatus** [comment]
Having a look at ffba289 it seems the button does nothing if tapped. But if you do so, it shows the default "tap" Android animation. This is confusing: if the animation is played, I would expect something to happen. Should be disabled.
