### ISSUE TITLE
Crash when visualising results with tests in progress

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-android#76]
On Android emulator, architecture i386, API 24, with 124f32c570 as the tip, you can sometimes provoke a crash by following this procedure (it occurred to me twice, once with another emulator and I am trying to understand how to make this more easily reproducible):

- run all tests concurrently
- as soon as http-invalid-request-line terminates, go to results view

When you're lucky (well, or unlucky, I guess that depends on your objective function), the app will crash like this:

```
03-20 16:00:49.860 2252-2252/org.openobservatory.ooniprobe E/AndroidRuntime: FATAL EXCEPTION: main
 Process: org.openobservatory.ooniprobe, PID: 2252
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
     at org.openobservatory.ooniprobe.data.TestStorage.loadTestsReverse(TestStorage.java:69)
     at org.openobservatory.ooniprobe.fragment.PastTestsFragment.updateList(PastTestsFragment.java:94)
     at org.openobservatory.ooniprobe.fragment.PastTestsFragment.onResume(PastTestsFragment.java:51)
     at android.support.v4.app.Fragment.performResume(Fragment.java:2235)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
     at android.os.Handler.handleCallback(Handler.java:751)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6077)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Also, interestingly, this *does not* cause the measurement to be stopped with API 24.

**Comment by bassosimone** [comment]
Also interestingly (again, it depends on the objective function) the app is so fucked up after the above described event that it cannot run web-connectivity ("missing input file") and that any attempt to access the results cause the app to crash with the same error as above.

**Comment by bassosimone** [comment]
I'm trying this diff to avoid the null pointer exception:

```diff
--- a/app/src/main/java/org/openobservatory/ooniprobe/data/TestStorage.java
+++ b/app/src/main/java/org/openobservatory/ooniprobe/data/TestStorage.java
@@ -66,7 +66,13 @@ public class TestStorage {
         NetworkMeasurement[] favoriteItems = gson.fromJson(jsonTests,NetworkMeasurement[].class);
         for (int i = 0; i < favoriteItems.length; i++){
             NetworkMeasurement current = favoriteItems[i];
-            if (!current.running)
+            if (current == null) {
+                /*
+                 * Avoids a crash; see:
+                 *
+                 * https://github.com/TheTorProject/ooniprobe-android/issues/76
+                 */
+            } else if (!current.running)
                 tests.add(current);
             else if (TestData.getInstance(activity, activity).getTestWithName(current.testName) == null)
                 tests.add(current);
```

**Comment by bassosimone** [comment]
What is really not clear to me is why the test list disappears. I don't think this has to do with measurement-kit, given that [the file is opened using a std::ifstream](https://github.com/measurement-kit/measurement-kit/blob/master/src/libmeasurement_kit/nettests/utils_impl.hpp#L18), i.e. an input stream.

**Comment by bassosimone** [comment]
Alright, now I'm trying another approach. I'll catch the exception and see what happens. (I know this sounds very ghetto, but I'm not planning on actually committing this; just a test).

**Comment by bassosimone** [comment]
Oh my, I figured it out and I have to admit that I am *very* surprised. This is the a-ha diff:

```diff
diff --git a/app/src/main/java/org/openobservatory/ooniprobe/data/TestStorage.java b/app/src/main/java/org/openobservatory/ooniprobe/data/TestStorage.java
index 54c890f..dcac520 100644
--- a/app/src/main/java/org/openobservatory/ooniprobe/data/TestStorage.java
+++ b/app/src/main/java/org/openobservatory/ooniprobe/data/TestStorage.java
@@ -18,6 +18,7 @@ import java.util.Iterator;
 import java.util.List;
 import java.util.Set;
 import java.util.stream.Collectors;
+import android.util.Log;
 
 public class TestStorage {
     public static final String PREFS_NAME = "OONIPROBE_APP";
@@ -64,14 +65,21 @@ public class TestStorage {
         String jsonTests = settings.getString(TESTS, null);
         Gson gson = new Gson();
         NetworkMeasurement[] favoriteItems = gson.fromJson(jsonTests,NetworkMeasurement[].class);
-        for (int i = 0; i < favoriteItems.length; i++){
-            NetworkMeasurement current = favoriteItems[i];
-            if (!current.running)
-                tests.add(current);
-            else if (TestData.getInstance(activity, activity).getTestWithName(current.testName) == null)
-                tests.add(current);
-            else if (TestData.getInstance(activity, activity).getTestWithName(current.testName).test_id != current.test_id)
-                tests.add(current);
+        for (int i = 0; i < favoriteItems.length; i++) {
+            try {
+                NetworkMeasurement current = favoriteItems[i];
+                if (current.running == null) {
+                    Log.d("xyz", "ouch this strikes me");
+                }
+                if (!current.running)
+                    tests.add(current);
+                else if (TestData.getInstance(activity, activity).getTestWithName(current.testName) == null)
+                    tests.add(current);
+                else if (TestData.getInstance(activity, activity).getTestWithName(current.testName).test_id != current.test_id)
+                    tests.add(current);
+            } catch (NullPointerException exc) {
+                Log.e("xx", exc.toString());
+            }
         }
         Collections.reverse(tests);
         return tests;
```

And this is the log:

```
03-21 10:11:12.684 16454-16454/org.openobservatory.ooniprobe D/xyz:
  ouch this strikes me
03-21 10:11:12.684 16454-16454/org.openobservatory.ooniprobe E/xx:
  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean
    java.lang.Boolean.booleanValue()' on a null object reference
```

![wpid-case-closed-stamp_645x400](https://cloud.githubusercontent.com/assets/337298/24140076/04b0286c-0e1f-11e7-9f0b-548a340586f2.png)

**Comment by bassosimone** [comment]
Okay, now it's time to understand why the hell the test list is missing. Let's see:
