### ISSUE TITLE
Calligrafy crash with Nexus S, API 13, armeabi emulator

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-android#86]
Hello! While testing v1.1.4-dev on Nexus S, API 13, armeabi emulator I see this easily reproducible crash that happens every time the app finishes the on-boarding procedure on such emulated device.

By reading the error, it seems to me that Calligrafy expects a specific compatibility class that is actually not present in the emulator. I did not experience this issue with previous versions of the app.

Relevant (in my opinion) snippet of the crash log:

```
Caused by: java.lang.NoClassDefFoundError: android.support.v7.widget.SwitchCompat$1
                                                                               at android.support.v7.widget.SwitchCompat.<clinit>(SwitchCompat.java:102)
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:416) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:576) 
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
```
This is the full log of the crash:

```
05-03 18:32:50.075 435-435/org.openobservatory.ooniprobe W/dalvikvm: VFY: unable to resolve virtual method 18914: Landroid/widget/CompoundButton;.onPopulateAccessibilityEvent (Landroid/view/accessibility/AccessibilityEvent;)V
05-03 18:32:50.085 435-435/org.openobservatory.ooniprobe D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
05-03 18:32:50.085 435-435/org.openobservatory.ooniprobe W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Landroid/support/v7/widget/SwitchCompat;
05-03 18:32:50.085 435-435/org.openobservatory.ooniprobe W/dalvikvm: Class init failed in Constructor.constructNative (Landroid/support/v7/widget/SwitchCompat;)
05-03 18:32:50.095 435-435/org.openobservatory.ooniprobe D/AndroidRuntime: Shutting down VM
05-03 18:32:50.095 435-435/org.openobservatory.ooniprobe W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40014760)
05-03 18:32:50.105 435-435/org.openobservatory.ooniprobe E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           java.lang.ExceptionInInitializerError
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:416)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:576)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:664)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:724)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:391)
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage5Fragment.onCreateView(IConsentPage5Fragment.java:63)
                                                                               at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                               at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                               at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                               at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                               at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                               at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                               at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
                                                                               at me.panavtec.wizard.Wizard.navigateNext(Wizard.java:94)
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage4Fragment.next(IConsentPage4Fragment.java:110)
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage4Fragment.access$000(IConsentPage4Fragment.java:20)
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage4Fragment$1.onClick(IConsentPage4Fragment.java:66)
                                                                               at android.view.View.performClick(View.java:3110)
                                                                               at android.view.View$PerformClick.run(View.java:11934)
                                                                               at android.os.Handler.handleCallback(Handler.java:587)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                               at android.os.Looper.loop(Looper.java:132)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4123)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:491)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.NoClassDefFoundError: android.support.v7.widget.SwitchCompat$1
                                                                               at android.support.v7.widget.SwitchCompat.<clinit>(SwitchCompat.java:102)
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:416) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:576) 
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:664) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:724) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:727) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:479) 
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:391) 
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage5Fragment.onCreateView(IConsentPage5Fragment.java:63) 
                                                                               at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192) 
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                                               at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                                               at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) 
                                                                               at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) 
                                                                               at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) 
                                                                               at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) 
                                                                               at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013) 
                                                                               at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763) 
                                                                               at me.panavtec.wizard.Wizard.navigateNext(Wizard.java:94) 
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage4Fragment.next(IConsentPage4Fragment.java:110) 
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage4Fragment.access$000(IConsentPage4Fragment.java:20) 
                                                                               at org.openobservatory.ooniprobe.fragment.IConsentPage4Fragment$1.onClick(IConsentPage4Fragment.java:66) 
                                                                               at android.view.View.performClick(View.java:3110) 
                                                                               at android.view.View$PerformClick.run(View.java:11934) 
                                                                               at android.os.Handler.handleCallback(Handler.java:587) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                               at android.os.Looper.loop(Looper.java:132) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4123) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:491) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
05-03 18:32:50.125 72-78/system_process W/ActivityManager:   Force finishing activity org.openobservatory.ooniprobe/.activity.InformedConsentActivity
05-03 18:32:50.125 72-78/system_process W/WindowManager: Failure taking screenshot for (230x383) to layer 21010
05-03 18:32:50.645 72-81/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{40a806a8 org.openobservatory.ooniprobe/.activity.InformedConsentActivity}
05-03 18:32:54.745 435-435/org.openobservatory.ooniprobe I/Process: Sending signal. PID: 435 SIG: 9
```

**Comment by bassosimone** [comment]
@lorenzoPrimi: if I understand it correctly, we're going to remove support for API < 14, right? In such case, then probably we can safely close this issue as not relevant anymore.
